invest_bi:
  outputs:
    dev:
      dataset: default
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-north1
      method: oauth
      priority: interactive
      project: xnwk-462111
      threads: 4
      type: bigquery
  target: dev
