# Docker file for running dbt Python model on Dataproc
FROM python:3.11-slim

RUN pip install --upgrade pip && \
    pip install pandas numpy numpy-financial

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
