name: dbt daily update purchase amounts

on:
  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt-bigquery
        run: pip install dbt-bigquery

      - name: Install dbt dependencies
        run: dbt deps
      
      - name: Write service account key
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FOR_DBT }}' > gcp_key.json

      - name: Run dbt
        run: dbt run -s +fct_purchase_amounts --profiles-dir ./profiles
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_key.json
