name: dbt daily run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 05:00 UTC

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt-bigquery
        run: pip install dbt-bigquery

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt
        run: dbt run --profiles-dir ./profiles
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FOR_DBT }}
